approval_policy = "on-request"

model_reasoning_effort = "medium"
personality = "pragmatic"

default_permissions = "workspace-only"

[permissions.workspace-only]
extends = ":workspace"

[permissions.workspace-only.filesystem]
":root" = "read"
":minimal" = "read"
"/home/gbi/.nvm/versions/node/v24.15.0/lib/node_modules/@openai/codex/node_modules/@openai/codex-linux-x64/vendor/x86_64-unknown-linux-musl/bin/codex" = "read"

[permissions.workspace-only.network]
enabled = true

[shell_environment_policy]
inherit = "core"
include_only = ["PATH", "HOME", "USER", "SHELL", "LANG", "LC_ALL", "TERM"]

[tui]
status_line = ["current-dir", "git-branch", "model-with-reasoning", "context-remaining", "weekly-limit", "five-hour-limit"]
notifications = ["agent-turn-complete", "approval-requested"]
notification_method = "bel"
notification_condition = "unfocused"
status_line_use_colors = true

[tui.model_availability_nux]
"gpt-5.5" = 4

[projects."/home/gbi/GitHub/Gabriel-Ladzaretti/vlt-cli"]
trust_level = "trusted"

[projects."/home/gbi/GitHub/mend/renovate-pro"]
trust_level = "trusted"

[projects."/home/gbi/GitHub/mend/renovate-ce-ee"]
trust_level = "trusted"

[projects."/home/gbi/GitHub/mend/renovate-pro-helm"]
trust_level = "trusted"

[projects."/home/gbi/GitHub/mend/renovate-server"]
trust_level = "trusted"

[projects."/home/gbi/GitHub/mend/rre"]
trust_level = "trusted"

[projects."/home/gbi/GitHub/mend/developer-platform"]
trust_level = "trusted"

[projects."/home/gbi/GitHub/Gabriel-Ladzaretti/ubuntu-yt-dlp"]
trust_level = "trusted"

[projects."/home/gbi/Downloads/fireman-sam-songs"]
trust_level = "trusted"

[projects."/home/gbi/GitHub/Reproductions/automerge"]
trust_level = "trusted"

[projects."/home/gbi/GitHub/Gabriel-Ladzaretti/renovate"]
trust_level = "trusted"

[projects."/home/gbi/GitHub/Gabriel-Ladzaretti/flatpak-steam-utils"]
trust_level = "trusted"

[projects."/home/gbi/GitHub/Gabriel-Ladzaretti/home-lab-deploy"]
trust_level = "trusted"

[projects."/home/gbi/GitHub/Gabriel-Ladzaretti/qmk_firmware"]
trust_level = "trusted"

[projects."/home/gbi"]
trust_level = "trusted"

[features]
apps = false

[mcp_servers.atlassian-rovo-mcp]
url = "https://mcp.atlassian.com/v1/mcp/authv2"

