[vault]
session_duration='2m'

[clipboard]
copy_cmd="wl-copy"
paste_cmd="wl-paste"

[pipeline]
find_pipe_cmd=["sh", "-c" ,"fzf --header-lines=1 | awk '{print $1}' | xargs -r vlt show -c --id"]

[hooks]
post_login_cmd=["fish","-c","vault_git pull"]
post_write_cmd=["fish","-c","vault_git add -u && vault_git commit -m \"$(date +'%Y-%m-%d %H:%M:%S')\" && vault_git push"]
