[vault]
session_duration='2m'
max_history_snapshots=1

[clipboard]
copy_cmd=["wl-copy"]
paste_cmd=["wl-paste","--no-newline"]

[hooks]
post_login_cmd=['fish','-c','vault_git pull']
post_write_cmd=['fish','-c',"vault_git add -u && vault_git commit -m \"$(date +'%Y-%m-%d %H:%M:%S')\" && vault_git push"]
