[terminal.shell]
program = "/usr/bin/bash"

[cursor]
blink_interval=500
blink_timeout=0
unfocused_hollow=true

[cursor.style]
blinking="Always"
shape="Block"

[window]
decorations = "Full"
opacity = 0.98

[window.padding]
x = 1
y = 1

[window.dimensions]
columns = 100
lines = 28

[font]
size = 15

[font.normal]
family = "Hack Nerd Font"

[font.offset]
y = 5

[general]
import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
  "~/.config/alacritty/user-theme.toml"
]

[terminal]


