import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
  "~/.config/alacritty/user-theme.toml"
]

[shell]
program = "/usr/bin/bash"

[window]
decorations = "Full"
opacity = 0.96

[window.padding]
x = 1
y = 1

[window.dimensions]
columns = 90
lines = 28

[font]
size = 15

[font.normal]
family = "Hack Nerd Font"

[font.offset]
y = 5


