[colors.primary]
background = "#272727"
foreground = "#FFFFFF"

[colors.normal]
black = "#585B70"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#89DDFF"
white = "#FFFFFF"

[colors.bright]
black = "#585B70"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#89DDFF"
white = "#FFFFFF"
